### PR TITLE
Added suppot for armv6l and armv7l

### PR DESCRIPTION
**Pull request by genebean**

### CODE REVIEW

**Comment by genebean** [comment]
I'll test this on a Raspberry Pi tonight.

**Review by danielparks — APPROVED** [review]
Lookin' good. I'll give you merge on this repo so you can hit the button after you've tested it.

**Comment by genebean** [comment]
noop run looks good to me:

```puppet
➜  ~ sudo -i puppet apply /home/pi/pipelines_test.pp --noop
Notice: Compiled catalog for pumpkinpi.home.technicalissues.us in environment production in 2.46 seconds
Notice: /Stage[main]/Pipelines::Agent::Unix/User[distelli]/home: current_value /home/distelli, should be /opt/distelli (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/User[distelli]/comment: current_value , should be Puppet Pipelines User (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/User[distelli]/shell: current_value , should be /bin/false (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/File[/etc/sudoers.d/distelli]/mode: current_value 0440, should be 0400 (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/File[/opt/distelli]/ensure: current_value absent, should be directory (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/Archive[/opt/distelli/distelli.Linux-armv7l-3.66.45.gz]/ensure: current_value absent, should be present (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/File[/opt/distelli/distelli.Linux-armv7l-3.66.45]/ensure: current_value absent, should be file (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/File[/opt/distelli/distelli]/ensure: current_value absent, should be link (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/File[/etc/distelli.yml]/ensure: current_value absent, should be file (noop)
Notice: /Stage[main]/Pipelines::Agent::Unix/Exec[pipelines::agent::unix Test agent executable]: Would have triggered 'refresh' from 1 events
Error: /Stage[main]/Pipelines::Agent::Unix/Exec[pipelines::agent::unix Install agent]: Could not evaluate: Could not find command '/opt/distelli/distelli'
Notice: /Stage[main]/Pipelines::Agent::Unix/Exec[pipelines::agent::unix Install agent]: Would have triggered 'refresh' from 1 events
Notice: /Stage[main]/Pipelines::Agent::Unix/Service[distelli-agent]: Dependency Exec[pipelines::agent::unix Install agent] has failures: true
Warning: /Stage[main]/Pipelines::Agent::Unix/Service[distelli-agent]: Skipping because of failed dependencies
Notice: Applied catalog in 0.18 seconds
```
What do you think @danielparks ?

**Comment by danielparks** [comment]
Still works on amd64! Merging.

**Pull request merged**
